//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCProShirts.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TCProShirts.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;_id&quot;:&quot;587d0d8ff43ea40e13382dad&quot;,&quot;printSize&quot;:&quot;general-standard&quot;,&quot;type&quot;:&quot;shirt&quot;,&quot;category&quot;:&quot;garment&quot;,&quot;code&quot;:&quot;TC0&quot;,&quot;name&quot;:&quot;Classic T-Shirt&quot;,&quot;templates&quot;:[{&quot;name&quot;:&quot;front&quot;,&quot;id&quot;:&quot;unisex-crewneck-tshirt-v2-front&quot;,&quot;required&quot;:true,&quot;sizes&quot;:[{&quot;size&quot;:&quot;all&quot;}],&quot;sides&quot;:[{&quot;side&quot;:&quot;front&quot;}]},{&quot;name&quot;:&quot;back&quot;,&quot;id&quot;:&quot;unisex-crewneck-tshirt-v2-back&quot;,&quot;required&quot;:true,&quot;sizes&quot;:[{&quot;size&quot;:&quot;all&quot;}],&quot;sides&quot;:[{&quot;side&quot;:&quot;back&quot;}]},{&quot;name&quot;:&quot;lifestyle-mens-crewneck-back-1&quot;,&quot;id&quot;:&quot;lifestyle-mens-crewneck-back-1&quot;,&quot;sizes&quot;:[{&quot;size&quot;:&quot;all&quot;}],&quot;sides&quot;:[{ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string bulkCode {
            get {
                return ResourceManager.GetString("bulkCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;_id&quot;:&quot;59239c6fdb7ba206dbaffe81&quot;,&quot;url&quot;:&quot;https://s3-us-west-2.amazonaws.com/sl-development/uploads/2017/05/17/00218c1e9dd31f4.png&quot;,&quot;image&quot;:&quot;https://s3-us-west-2.amazonaws.com/sl-development/uploads/2017/05/17/00218c1e9dd31f4.png&quot;,&quot;description&quot;:&quot;Colleges in the United States&quot;,&quot;name&quot;:&quot;Colleges&quot;,&quot;fullName&quot;:&quot;Colleges (USA)&quot;,&quot;slug&quot;:&quot;usa-colleges&quot;,&quot;children&quot;:[{&quot;tagId&quot;:&quot;59239c6fdb7ba206dbaffe83&quot;,&quot;slug&quot;:&quot;usa-colleges-a_to_e&quot;},{&quot;tagId&quot;:&quot;59239c6fdb7ba206dbaffe84&quot;,&quot;slug&quot;:&quot;usa-colleges-f_to_j&quot;},{&quot;tagId&quot;:&quot;59239c6fdb7ba [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string category {
            get {
                return ResourceManager.GetString("category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string dataThemes {
            get {
                return ResourceManager.GetString("dataThemes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;poster&quot;:{&quot;designId&quot;:&quot;@DesignID&quot;,&quot;entityId&quot;:&quot;@EntityID&quot;,&quot;printSize&quot;:&quot;poster-standard&quot;,&quot;id&quot;:&quot;@TimeSpanID-36710&quot;,&quot;sides&quot;:{&quot;front&quot;:{&quot;artworkId&quot;:&quot;@ArtworkID&quot;,&quot;position&quot;:{&quot;vertical&quot;:{&quot;origin&quot;:&quot;C&quot;,&quot;offset&quot;:0},&quot;horizontal&quot;:{&quot;origin&quot;:&quot;C&quot;,&quot;offset&quot;:0}},&quot;size&quot;:{&quot;width&quot;:0.85,&quot;unit&quot;:&quot;percentage&quot;}}},&quot;handling&quot;:&quot;default&quot;},&quot;case&quot;:{&quot;designId&quot;:&quot;@DesignID&quot;,&quot;entityId&quot;:&quot;@EntityID&quot;,&quot;printSize&quot;:&quot;case-standard&quot;,&quot;id&quot;:&quot;@TimeSpanID-38916&quot;,&quot;sides&quot;:{&quot;front&quot;:{&quot;artworkId&quot;:&quot;@ArtworkID&quot;,&quot;position&quot;:{&quot;vertical&quot;:{&quot;origin&quot;:&quot;C&quot;,&quot;offset&quot;:-0.002 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string template {
            get {
                return ResourceManager.GetString("template", resourceCulture);
            }
        }
    }
}
